### ISSUE TITLE
README.md Errors

### ISSUE THREAD

**Issue by flywire** [kevdagoat/ash-additional-commands#2]
1) README.md refers to `/bin/ledctl` but file is `/bin/ledcontrol`
2) README.md refers to `/bin/systemcl` but file is `/bin/systemctl`
3) Expecting scripts to have `.sh` extension
4) No usage instructions

**Comment by kevdagoat** [comment]
Didn’t notice this....

**Comment by kevdagoat** [comment]
Fixed
